#!/bin/bash
# Currently these changes are not yet merged in the official pyiron_base version - last update 04.02.2024 - 11:14
pip install git+https://github.com/pyiron/pyiron_base.git@nfdi4ing --no-deps --no-build-isolation
